<a href="https://colab.research.google.com/github/afif-af/hanson_ml_scikitlearn_tensorflow/blob/main/chapter09handson_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

X,y=make_blobs(n_samples=300, random_state=42,centers=3,cluster_std=1.0)
k=5
kmeans=KMeans(n_clusters=k,random_state=42)
y_pred=kmeans.fit_predict(X)


In [35]:
y_pred

array([1, 1, 0, 3, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 3, 0, 0, 0, 0,
       2, 1, 0, 4, 4, 3, 2, 0, 0, 0, 1, 0, 4, 0, 1, 2, 1, 3, 2, 0, 1, 3,
       0, 0, 1, 3, 1, 2, 2, 4, 1, 0, 4, 3, 1, 0, 3, 0, 4, 2, 2, 4, 4, 3,
       3, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 3, 0, 2, 0, 0, 1, 0, 2, 1, 4, 0,
       2, 0, 1, 0, 4, 0, 0, 1, 1, 0, 1, 4, 3, 0, 3, 0, 0, 0, 0, 0, 2, 1,
       2, 0, 0, 0, 0, 2, 1, 3, 1, 3, 3, 2, 0, 4, 1, 1, 4, 0, 1, 1, 0, 0,
       0, 0, 0, 3, 2, 1, 0, 1, 0, 0, 4, 0, 3, 3, 2, 0, 2, 0, 0, 4, 2, 4,
       0, 3, 2, 1, 1, 0, 0, 1, 4, 1, 0, 1, 3, 0, 0, 0, 0, 0, 3, 0, 3, 3,
       2, 0, 2, 2, 1, 0, 4, 2, 3, 1, 2, 0, 3, 3, 4, 1, 3, 1, 3, 3, 2, 2,
       0, 4, 0, 0, 3, 3, 0, 3, 1, 1, 3, 0, 0, 4, 2, 3, 1, 4, 4, 1, 0, 1,
       1, 3, 1, 1, 0, 3, 1, 4, 3, 0, 0, 4, 0, 1, 2, 2, 1, 3, 4, 1, 4, 2,
       2, 0, 4, 3, 2, 3, 1, 2, 1, 3, 1, 2, 2, 1, 3, 0, 4, 0, 0, 0, 1, 0,
       2, 3, 4, 2, 2, 0, 0, 2, 3, 2, 4, 1, 4, 0, 0, 0, 3, 3, 2, 3, 1, 2,
       4, 2, 3, 1, 0, 3, 2, 0, 1, 0, 3, 0, 4, 4], d

In [36]:
y_pred is kmeans.labels_

True

In [37]:
kmeans.cluster_centers_

array([[-2.63323268,  9.04356978],
       [-7.14263624, -7.53499139],
       [ 5.48251412,  1.61493664],
       [ 4.01169263,  2.40625191],
       [-6.40330923, -5.96068499]])

In [38]:
import numpy as np
X_new=np.array([[0,2],[3,2],[-3,3],[-3,2.5]])
kmeans.predict(X_new)

array([3, 3, 0, 0], dtype=int32)

In [39]:
kmeans.transform(X_new).round(2)

array([[ 7.52, 11.91,  5.5 ,  4.03, 10.22],
       [ 9.02, 13.92,  2.51,  1.09, 12.32],
       [ 6.05, 11.32,  8.59,  7.04,  9.59],
       [ 6.55, 10.86,  8.53,  7.01,  9.12]])

In [40]:
good_init=np.array([[-3,3],[-3,2],[-3,1],[-1,2],[0,2]])
kmeans=KMeans(n_clusters=5,init=good_init,n_init=1, random_state=42)
kmeans.fit(X)

KMeans(init=array([[-3,  3],
       [-3,  2],
       [-3,  1],
       [-1,  2],
       [ 0,  2]]),
       n_clusters=5, n_init=1, random_state=42)

In [41]:
kmeans.inertia_

444.8914878525166

In [42]:
kmeans.score(X)

-444.8914878525166

In [43]:
from sklearn.cluster import MiniBatchKMeans

minibatch_kmeans=MiniBatchKMeans(n_clusters=5, random_state=42)
minibatch_kmeans.fit(X)

MiniBatchKMeans(n_clusters=5, random_state=42)

In [44]:
from sklearn.metrics import silhouette_score

silhouette_score(X, kmeans.labels_)

np.float64(0.6876456959936664)

In [45]:
# from google.colab import files
# uploaded=files.upload()

In [46]:
import PIL
image=np.asarray(PIL.Image.open('/content/IMG_9862.PNG'))

In [47]:
image.shape

(5184, 3456, 3)

In [48]:
X=image.reshape(-1, 3)
kmeans=KMeans(n_clusters=8, random_state=42).fit(X)
segmented_img=kmeans.cluster_centers_[kmeans.labels_]
segmented_img=segmented_img.reshape(image.shape)

In [49]:
from sklearn.datasets import load_digits
X_digits, y_digits = load_digits(return_X_y=True)
X_train, y_train = X_digits[:1400], y_digits[:1400]
X_test, y_test = X_digits[1400:], y_digits[1400:]

In [50]:
from sklearn.linear_model import LogisticRegression
n_labeled = 50
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_train[:n_labeled], y_train[:n_labeled])

LogisticRegression(max_iter=10000)

In [51]:
log_reg.score(X_test, y_test)

0.7581863979848866

In [53]:
k=50
kmeans=KMeans(n_clusters=k, random_state=42)
X_digits_dist=kmeans.fit_transform(X_train)
representative_digit_idx=np.argmin(X_digits_dist, axis=0)
X_representative_digits=X_train[representative_digit_idx]

In [58]:
y_representative_digits=np.array([1,3,6,0,7,9,2,5,1,9,9,3,7,
                                  1,3,6,0,7,9,2,5,1,9,9,3,7,
                                  1,3,6,0,7,9,2,5,1,9,9,3,7,
                                  1,3,6,0,7,9,2,5,1,5,3])


In [59]:
log_reg=LogisticRegression(max_iter=10000)
log_reg.fit(X_representative_digits, y_representative_digits)

LogisticRegression(max_iter=10000)

In [60]:
log_reg.score(X_test, y_test)

0.1889168765743073

In [62]:
y_train_propagated=np.empty(len(X_train), dtype=np.int64)
for i in range(k):
  y_train_propagated[kmeans.labels_==i]=y_representative_digits[i]

In [63]:
log_reg=LogisticRegression()
log_reg.fit(X_train, y_train_propagated)
log_reg.score(X_test, y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.12846347607052896

In [64]:
percentile_closest = 99

X_cluster_dist = X_digits_dist[np.arange(len(X_train)), kmeans.labels_]
for i in range(k):
  in_cluster = (kmeans.labels_ == i)
  cluster_dist = X_cluster_dist[in_cluster]
  cutoff_distance = np.percentile(cluster_dist, percentile_closest)
  above_cutoff = (X_cluster_dist > cutoff_distance)
  X_cluster_dist[in_cluster & above_cutoff] = -1
  partially_propagated = (X_cluster_dist != -1)

X_train_partially_propagated = X_train[partially_propagated]
y_train_partially_propagated = y_train_propagated[partially_propagated]

In [65]:
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_train_partially_propagated, y_train_partially_propagated)
log_reg.score(X_test, y_test)

0.1309823677581864

In [66]:
(y_train_partially_propagated == y_train[partially_propagated]).mean()

np.float64(0.11703703703703704)